### ISSUE TITLE
NPC Automation (FGU & FGC)

### ISSUE THREAD

**Issue by mostcallmetim** [BeeGrinder/FantasyGrounds-SW5e#13]
Some of the NPC's are not working properly. For example, the Trooper, Scout's Hold-out blaster says "Hit: 4 (1d4+2)." So, it won't do damage in the combat tracker. If I copy and edit the statblock, to say "Hit: 4 (1d4+2) energy damage." it works.

There are some other minor errors on NPC's that use spells. For FG to automate NPC spell attacks, the spell needs to say spell attack instead of tech attack in the spell description. This is a problem on a number of spells like Choke, where it says "Make a ranged force attack". If you edit it to "Make a ranged spell attack" FG will allow you to roll the NPC's attack from the combat tracker.

Will you be making further updates or is this something we should just change on our own?

Thanks for all your work.

**Comment by BeeGrinder** [comment]
Thanks.  I'll be doing bug fixes for sure.  Was this on FG classic or FGU?

**Comment by mostcallmetim** [comment]
Oh, I didn't know this would even work in Unity. This was in Classic, but I would think the same applies to Unity for the word recognition stuff.

**Comment by BeeGrinder** [comment]
Yes, I've updated several issues with FGU that were an issue when it was release to beta testers.  So far, it seems to work.  Looks like the issues you are reporting are due to the way FG parses the wording into an automated action.  Which has been (and probably will remain) frustrating to figure out.  But, it does seem to be the same in FGU and FGC.

**Comment by BeeGrinder** [comment]
@mostcallmetim please download the latest modules from this site and test the two issues (Scout and spell attack).  I think they are solved.  I also discovered Operative Practice is popping up for selection correctly at level 3, so I need to look into that.

**Comment by BeeGrinder** [comment]
No negative feedback. Closing issue.
