### ISSUE TITLE
Update Consular class

### ISSUE THREAD

**Issue by BeeGrinder** [BeeGrinder/FantasyGrounds-SW5e#18]
Update Consular class to current

We've found something with the Consular class: there is no Way of Suggestion for the level 3 prompt selection, and in the Way of Lighting, the Electric Attunement has the word Affinity on it instead

**Comment by lordcygnus** [comment]
Hey, here are all the updates for the Consular class, setup as the Class.txt file.
[ConsularClassUpdate.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5631820/ConsularClassUpdate.txt)

**Comment by BeeGrinder** [comment]
Edited into class.txt.  Thanks!
