### ISSUE TITLE
Unable to attack with new damage type in CT/NPC sheet

### ISSUE THREAD

**Issue by thejazzmann** [BeeGrinder/FantasyGrounds-SW5e#2]
In both combat tracker and from an NPC sheet directly, the DM is unable to roll for damage when a weapon contains the new damage types (i.e. energy, kinetic, etc.).

**Comment by BeeGrinder** [comment]
Added sw5e damage types to extension code.

**Comment by BeeGrinder** [comment]
extension had multiple typos.  should work now.
