### ISSUE TITLE
Update Engineer class

### ISSUE THREAD

**Issue by BeeGrinder** [BeeGrinder/FantasyGrounds-SW5e#20]
Check table for the Potent Aptitude values as a column (remove them from the Features Column) and change Slots to Modifications Slots.
Level 2 Tool Expertise instead of Tool Understanding.
Level 3 is missing the Gadgeteer Engineering and Astrotech Engineering is no longer there, replaced by Unstable Engineering (I'm checking and the Astrotech Engineering is at the Expanded Content, so I'm reviewing it as well)
Change Infuse Item at level 2 to Infuse Item (+1) and add Infuse Item (+2) at Level 10, Infuse Item (+3) at Level 15.

In the Armomerch Engineering:
* Level 6 Ability for the Armormech Engineering should be Extra Attack
* Remove Casting Celerity Level 14 and put Armomerch's Celerity instead.
* In the Armomerch Modifications:
- Absorption Shield should have the Physical Shield requirement instead of Light Shield Generator.
- Advanced power fist should have Armor as a requirement.
- Remove Armorweave Underlay.
- Artificially Intelligent should have level 9 and Armor requirements.
- Add Bonded Plates.
- Change Collapsible Suit requirement to Level 5 and Armor.
- Remove Dampening Overlay.
- Change Electroshock Shield requirement to Shield Generator instead of Heavy Shield.
- Change Infiltration Suit requirement to Armor instead of Light or Medium Armor. (Not sure about this)
- Change Overload Shield requirement to Shield Generator instead of Light or Medium Shield Generator.
- Change Prototype Power Fist requirement to Level 5, Armor instead of the current value.
- Add Reinforced Overlay.
- Shield Amplifier should only have Shield Generator as a requirement.
- Change Shield Cover to Shield Anchor.
- Change Weapon Integration to Weapon Integration Armoring.

In the Armstech Engineering:
* In the Armstech Modifications:
- Remove Augmented Steps.
- Change Burst Fire to Burst Core.
- Change Booming Strikes requirement to Level 5.
- Add Celerity Oscillator.
- Change Collapsible Hilt to Collapsible Frame.
- Add Improved Burst Core.
- Change Jagged Edge to Jagged Oscillator.
- Change Keen Edge to Keen Oscillator.
- Change Power Loop requirement to Level 9.
- Change Subdued Recoil to Recoil Dampener.
- Change Returning Weapon to Returning Weapon Guard.
- Change Shock Harpoon to Shocking Harpoon.
- Change Shocking Strike to Shocking Oscillator.
- Add Stabilizer Cell.
- Add Staggering Oscillator.
- Change Venomous Weapon for Venomous Oscillator.

In the Astrotech Engineering:
* In the Astrotech Upgrades change the wording to Astrotech Modifications:
- Add Analysis Protocol.
- Remove the Class 4 Droid Requirement from Back-Up Protocol.
- Add Darkvision Optics.
- Remove the Class 4 Droid Requirement from Emergency Mode.
- Remove the Level Requirement from the Four-Armed Combatant.
- Add Martial Protocol.
- Add Memory Protocol.
- Add Powerful Droid.
- Add Powerful Grip.
- Add the d6 Hit Die requirement to Premium Power Core.
- Add Truesight Optics.

**Comment by lordcygnus** [comment]
Finished up creating the Engineer file for the changes, pay special attention to the Astrotech Engineering because I don't know if the Droid Creation part is set up correctly lol, but like the other classes, here you go.
[EngineerClassUpdate.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5632179/EngineerClassUpdate.txt)

**Comment by BeeGrinder** [comment]
class.txt updated.  Thanks.
