### ISSUE TITLE
Update Fighter Class

### ISSUE THREAD

**Issue by BeeGrinder** [BeeGrinder/FantasyGrounds-SW5e#21]
Add the Martial Superiority column to the class table.
Add the Fighting Mastery at 3rd level (and possible reference to that particular feature list within chapter 6 of the PHB).
Add Heavy Weapon Specialist to the 3rd level Fighter Specialty prompt window (and all related information on that subclass)
Change Fighter Specialty to Fighter Specialty Feature at level 7th, 10th, 15th and 18th.

In the Assault Specialist:
* Change the Brute Force ability, new values for damage per level and updated requirement as well.
* Add Remarkable Athlete at 3rd level.
* Check the updated wording on the Brutish Durability 7th level ability.

In the Shield Specialist:
* Check and update the Techcasting new values for the known powers and wording within the feature.
* Add Stay in Formation.
* Check the fighter word typo on the Rallying Cry feature text.

In the Tactical Specialist:
* Check the wording and setup for the all features within the subclass, table for Tactical Specialist Superiority Dice and Maneuvers Known as well.
* Update Student of War to Bonus Proficiencies at 3rd level.
* Update the other 3rd level feature to Improved Combat Superiority.
- Add inside the Improved Combat Superiority:
. Improved Maneuvers.
. Improved Superiority Dice.
* Change Signature Maneuver to 3rd level.
* Change Greater Signature Maneuver to level 10th
* Add Maneuver Mastery at level 18th.

**Comment by lordcygnus** [comment]
Hey, just finished up the updates to the Fighter class based on the Class.txt file, I'm attaching the changes on this file here
[FighterClassUpdate.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5633906/FighterClassUpdate.txt)

**Comment by BeeGrinder** [comment]
class.txt updated. Thank you.
