### ISSUE TITLE
Update guardian class

### ISSUE THREAD

**Issue by BeeGrinder** [BeeGrinder/FantasyGrounds-SW5e#22]
Update class description word from Predator to Destroyer.
Update Class Table, Force Powers Known values and add Focused Strikes column as well.
Change Force Powered Strikes description, they have new values per level for the damage.
Move Guardian Aura to level 3 and add Fighting Style to Level 2.
Change Guardian Focus to Focus Feature at level 7, 15 and 20.
Add Guardian Aura (15 ft radius) to level 9.
Change Guardian Aura description to Guardian Aura (two auras) at level 10.
Add Guardian Aura (30 ft radius) at level 17.
Change Guardian Aura description to Guardian Aura (three auras) at level 18.
For the 3rd level prompt subclass selection, the current PHB has Makashi, Niman, Shien/Djem So, and Soresu
. We are missing Niman and Shien/Djem So forms completely, please add the two forms currently not present.
. Shii-choo is on the EC so I'm going to review it here as well.
Remove Aura of Devotion from the Guardian Aura list.

In the Form II - Makashi:
* Change the Fighting Style wording and title to Form Basics.
* Change the Channel The Force content from Advancing Defender to Makashi Riposte. (it has the Spec. Required as Form III - Soresu, so if the other one has the Makashi Riposte, just change it, going to review Soresu after)
* Glancing Blow content is repeated, remove the repeated part.

In the Form III - Soresu:
* Change the Fighting Style wording and title to Form Basics.

In the Form I - Shii-Cho:
* Change the Fighting Style wording and title to Form Basics.
* Need to separate the Channel The Force ability from The Way of The Sarlacc.
* Be sure to check the Channel the Force ability Disarming Strike.
* Change the DeterminatioN word for Determination in the Master of Determination level 20 ability.

**Comment by lordcygnus** [comment]
Attaching the file ready to be used for the Class Update
[GuardianClassUpdate.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5634163/GuardianClassUpdate.txt)

**Comment by BeeGrinder** [comment]
added to class.txt
