### ISSUE TITLE
Update Monk class

### ISSUE THREAD

**Issue by BeeGrinder** [BeeGrinder/FantasyGrounds-SW5e#23]
Check table values:
. Change Martial Arts Damage Die column to Martial Arts with dice values column.
. Add Monastic Vows column.
Add Monastic Vows to level 2 (and all related content), change Unarmored Movement to level 3 (also, new wording in the ability description)
Level 6 change Focused Strikes to Enhanced Strikes.
Move Purity of Body to level 13 and add Ability Score Improvement to level 10.
Change Monastic Order wording to Monastic Order Feature at level 6, 11 and 17.
Remove Tongue of the Sun and Moon from level 13.
Change Timeless Body to Timeless Vessel at level 15.
At the Martial Arts description, update new content.
Change the Focus description, update to new content for each ability.
At level 3, promtp subclass selector:
. remove Teras Kasi Order, doesn't exists anymore on any of the 5E content.
. Add Matukai and Crimson Orders to the selector (and all PHB Content related to these two orders).

In the Nightsister Order
* Ichor Lighting has a new content description, please change.
* Dark Magick description needs a change as well.

**Comment by lordcygnus** [comment]
Monk text file with updates ready as well, attaching here
[MonkClassUpdate.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5634345/MonkClassUpdate.txt)

**Comment by BeeGrinder** [comment]
added to class.txt
