### ISSUE TITLE
Scholar class update

### ISSUE THREAD

**Issue by BeeGrinder** [BeeGrinder/FantasyGrounds-SW5e#25]
At the class table:
. Check the values for the Academic Superiority and Discoveries columns, update needed.
Change Multitasker descriptor to updated one.
At level 3 Academic Pursuit prompt windows:
. Change the Physician word for Doctor in the first option and all related descriptors for it.
. Gambler pursuit is missing, add the option and all related content from the PHB.

In the Doctor Pursuit:
* Separate Remote Healer and all the Additional Maneuvers.
* Check last point on the Additional Maneuvers, add it and put all the content present for it from the Remote Healer feature.
* Change Discoveries-Physician Pursuit descriptor to Discoveries (Doctor).
- Put a reference link to the Side Effects table already created
- Change Scholar Physician Side Effects name and references if possible.

In the Politician Pursuit:
* The Additional Maneuvers are being referenced from another set of skills (probably the Tactician Pursuit), change it to have the content for the Politician Pursuit and update references.
* Change the wording for Discoveries-Politician to Discoveries (Politician).

In the Tactician Pursuit:
* Change the wording for Discoveries-Tactician to Discoveries (Tactician).

**Comment by lordcygnus** [comment]
Here it is, the scholar file for the class update.
[ScholarClassUpdate.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5638365/ScholarClassUpdate.txt)

**Comment by BeeGrinder** [comment]
added to class.txt
