### ISSUE TITLE
Berserker Class Update

### ISSUE THREAD

**Issue by lordcygnus** [BeeGrinder/FantasyGrounds-SW5e#26]
Hey, I'm creating an issue as the other ones, here is the Berserker class updated setup as with the Class.txt file.
[BerserkerClassUpdate.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5631827/BerserkerClassUpdate.txt)

**Comment by BeeGrinder** [comment]
Holy crap!  You are awesome!  Thanks.  I'll integrate these and debug ASAP!!

**Comment by BeeGrinder** [comment]
After some issues I had with the UTF-8 character set (I am on my work Mac and git was flagging all non-ascii characters for some reason) I ran par5e and it looks perfect!!!

One thing, before we go too much farther.  On my list of to-do's is to change the format of these "invocation" style lists of choice based skills.  Like berserker instincts.  If you look at my current "Armstech Modifications" they are a table, just like 5e invocations.  I'd like to convert any of these from a simple list to a table.  No biggie if you don't want to, I'll do it later, just figured you may want to do that too?

**Comment by lordcygnus** [comment]
Sure, let me check the listing on the other classes first, to transform the list elements to tables for all related possible lists. Once I set up a list to table on the other classes, we can update the 3 files that I've already created if that's ok with you.

**Comment by BeeGrinder** [comment]
Perfect... this is a bad way to message... my discord is BeeGrinder#1946
