### ISSUE TITLE
Update to Chapter 6: Customization Options

### ISSUE THREAD

**Issue by lordcygnus** [BeeGrinder/FantasyGrounds-SW5e#28]
I'm creating this issue to address the updates on all the content related to the Customization Options mapped at Chapter 6 of the PHB

**Comment by lordcygnus** [comment]
Updates to Fighting Styles
[FightingStyles.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5633914/FightingStyles.txt)

**Comment by lordcygnus** [comment]
Updates to Fighting Masteries
[FightingMasteries.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5633917/FightingMasteries.txt)

**Comment by lordcygnus** [comment]
Updates to Lightsaber Forms
[LightsaberForms.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5633918/LightsaberForms.txt)

**Comment by lordcygnus** [comment]
Updates to Feats
[Feats.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5633968/Feats.txt)

**Comment by BeeGrinder** [comment]
FYI. Those roll charts at the beginning of some of these are put into tables.txt for rollable tables.
I need to figure out how to link to the tables from the PHB pages.

**Comment by BeeGrinder** [comment]
I have added these to the Reference Manual as "Chapter 6" but this is just a text chapter.  For instance, the Feats.txt need special formatting to be available in the Feats button.  See par5e/input/feats.txt file for format example.

**Comment by BeeGrinder** [comment]
Looking at the 5e PHB, the fighting style list is just repeated in the feature for the specific class feature that grants a fighting style.  So, we will repeat rather than link.  There does not appear to be a generic list feature that multiple classes can link to in the FG file format.

**Comment by lordcygnus** [comment]
I'm going to review and update the feats.txt file according to the PAR5E template, probably going to do the same for backgrounds.txt; and sure, remove the repeated references to the Fighting Styles

**Comment by BeeGrinder** [comment]
I've figured out a way to link to the reference manual for fighting style, lightsaber form and fighting mastery.  So, each reference to chapter 6 will have a link to the appropriate list.

**Comment by BeeGrinder** [comment]
I think this is done.  Can you please confirm or let me know what I have missed.  Thank you.

**Comment by lordcygnus** [comment]
Fighting Styles and Masteries working, I'm not finding the Lightsaber Forms.

**Comment by BeeGrinder** [comment]
It's only where I found reference with my search... like Guardian->Niman Form->Form Basics
If I missed some, let me know and I will update it.

**Comment by lordcygnus** [comment]
Found them, but, if we can make them appear as something at an upper level, like a personalized table of some kind, would be better, because it's not something exclusive of the Guardian Class, It's kind of a Mastery or Style related thing.

**Comment by BeeGrinder** [comment]
The only place "lightsaber form" appears is in the guardian class.  But I put all these lists in the reference manual in the PHB library under "Chapter 6".
If other talents/sub-classes use it, what is it I should be searching on?

**Comment by lordcygnus** [comment]
Formfighting Style (a Fighting Style) is used by classes apart from the Guardian, and that allows the PC to select 3 lightsaber forms from the Lightsaber Forms list.

**Comment by lordcygnus** [comment]
Updated Feats list using feats.txt as a template
[Feats.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5648218/Feats.txt)

**Comment by BeeGrinder** [comment]
feats updated.  module posted.  closing.
