### ISSUE TITLE
Scout Class Update

### ISSUE THREAD

**Issue by lordcygnus** [BeeGrinder/FantasyGrounds-SW5e#29]
Issue created to update the Scout class to the latest on the PHB (and some of the EC)

**Comment by lordcygnus** [comment]
Class update file ready, attaching here.
[ScoutClassUpdate.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5638887/ScoutClassUpdate.txt)

**Comment by BeeGrinder** [comment]
added to class.txt
