### ISSUE TITLE
Sentinel Class Update

### ISSUE THREAD

**Issue by lordcygnus** [BeeGrinder/FantasyGrounds-SW5e#30]
As per the other updates, this one is created to address the class update for the Sentinel Class

**Comment by lordcygnus** [comment]
Sentinel Class update file
[SentinelClassUpdate.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5639269/SentinelClassUpdate.txt)

**Comment by BeeGrinder** [comment]
added to class.txt
