### ISSUE TITLE
Update to Races

### ISSUE THREAD

**Issue by lordcygnus** [BeeGrinder/FantasyGrounds-SW5e#31]
Just addressing some missing races on the races part of the PHB

**Comment by lordcygnus** [comment]
I've updated the races.txt file according to the format, in this version I've added the droid (classes 1 through 5) as available races (with their images as well). 
[races.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5640421/races.txt)
![species_droidclass01](https://user-images.githubusercontent.com/63756994/101118484-215d9300-35b7-11eb-8213-f62ad57dd59e.jpg)
![species_droidclass05](https://user-images.githubusercontent.com/63756994/101118485-21f62980-35b7-11eb-8285-d7f18d6240d2.jpg)
![species_droidclass04](https://user-images.githubusercontent.com/63756994/101118486-228ec000-35b7-11eb-86ca-64d8e19977aa.jpg)
![species_droidclass03](https://user-images.githubusercontent.com/63756994/101118487-228ec000-35b7-11eb-9817-b86eb507e274.jpg)
![species_droidclass02](https://user-images.githubusercontent.com/63756994/101118488-23275680-35b7-11eb-9bc1-84c30f407b46.jpg)

**Comment by BeeGrinder** [comment]
Add droid player races and portraits added.
