### ISSUE TITLE
Update to PHB Backgrounds

### ISSUE THREAD

**Issue by lordcygnus** [BeeGrinder/FantasyGrounds-SW5e#33]
Creating this one to update the missing backgrounds on the PHB end.

**Comment by lordcygnus** [comment]
Missing backgrounds here in the attached file.
[backgrounds.txt](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5647930/backgrounds.txt)

**Comment by BeeGrinder** [comment]
This appears to just be a list of backgrounds that need to be added.  Thanks I'll add them.
Can you look at the current list in the backgrounds button and see if any of the older ones need to be removed?

**Comment by BeeGrinder** [comment]
New ones added to backgrounds.txt

**Comment by lordcygnus** [comment]
Confirmed, missing PHB backgrounds now appearing.

**Comment by BeeGrinder** [comment]
Thanks. Closing
