### ISSUE TITLE
Guardian class fix.

### ISSUE THREAD

**Issue by BeeGrinder** [BeeGrinder/FantasyGrounds-SW5e#34]
For unknown reason, the link for the Channel the Force feature is not working.
Sub-class choice is not functioning.
Also, Guardian Focus ability appears to be repeating in the class window.  Looks like a mix up between features and sub-class ability tags.  But, I'm not sure.

**Comment by BeeGrinder** [comment]
Fixed and new PHB module released

**Comment by lordcygnus** [comment]
Level 3 Prompt window not appearing
