### ISSUE TITLE
Guardian Abilities Missing

### ISSUE THREAD

**Issue by thejazzmann** [BeeGrinder/FantasyGrounds-SW5e#7]
2nd level ability Guardian Aura exists, but entries for the auras themselves do not.

**Comment by thejazzmann** [comment]
Abilities for Channel the Force are also missing.

**Comment by BeeGrinder** [comment]
Added auras and their descriptions under a table in the aura section.  Listed the two channel abilities under "Channel the Force".  So, they should be readable from the character sheet.  Spell effects are not done for these yet.
